// <auto-generated />
using Hackbot.Services.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Hackbot.Migrations
{
    [DbContext(typeof(AdminCredentialsContext))]
    [Migration("20201104235333_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9");

            modelBuilder.Entity("Hackbot.Structures.Admin", b =>
                {
                    b.Property<ulong>("P_KEY")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("P_KEY");

                    b.ToTable("Admins");
                });
#pragma warning restore 612, 618
        }
    }
}
